name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Setup Python if you're deploying a Python API
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install API dependencies if requirements.txt exists
      - name: Install API dependencies
        run: |
          if [ -f api/GetVisitorCount/requirements.txt ]; then pip install -r api/GetVisitorCount/requirements.txt; fi

      - name: Deploy to Azure
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: "public"
          output_location: "public"
          skip_app_build: true
          api_location: "api/GetVisitorCount"
