name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Optional: Setup Python if your API uses Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Optional: Install API dependencies (for local testing only, Azure will handle it during deployment)
      - name: Install API dependencies
        run: |
          if [ -f api/GetVisitorCount/requirements.txt ]; then pip install -r api/GetVisitorCount/requirements.txt; fi

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          app_location: "public"
          api_location: "api/GetVisitorCount"
          output_location: "public"
          skip_app_build: true
