name: Deploy Cloud Resume

on:
  push:
    branches: [main]
    paths:
      - 'public/**'
      - 'api/**'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: ${{ steps.deployment.outputs.static_web_app_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Validate directory structure
        run: |
          echo "Verifying project structure..."
          [ -d "public" ] || { echo "Error: 'public' directory missing"; exit 1; }
          [ -f "public/index.html" ] || { echo "Error: index.html missing"; exit 1; }
          [ -d "api" ] || { echo "Error: 'api' directory missing"; exit 1; }

      - name: Deploy to Azure Static Web Apps
        id: deployment
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: "public"
          api_location: "api"
          output_location: ""
          skip_app_build: true
          skip_api_build: false
          verbose: true
          deployment_environment: production

      - name: Verify deployment
        run: |
          if [ -z "${{ steps.deployment.outputs.static_web_app_url }}" ]; then
            echo "::error::Deployment failed - no URL generated"
            exit 1
          else
            echo "Deployment successful!"
            echo "URL: ${{ steps.deployment.outputs.static_web_app_url }}"
          fi
