name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # For Python Function (if needed)
      - name: Setup Python
        if: contains('api/GetVisitorCount', inputs.api_location)
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Main Deployment
      - name: Deploy to Azure
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: "public"               # Points to your public folder
          output_location: "public"           # Same as app_location
          skip_app_build: true                # No build step needed
          api_location: "api/GetVisitorCount" # Your API folder
          routes_location: "public/routes.json" # Optional for custom routes
